#!/usr/bin/env python3
"""Generate a subset of the Material Design Icons webfont embedded as a C header.

Scans the given C/C++ source files for ICON_MDI_* identifiers that are actually
referenced, maps each to its codepoint via the IconFontCppHeaders defines file,
subsets materialdesignicons-webfont.ttf down to just those glyphs, and writes the
result as a byte array (icon_font_data.h). The full font is ~1.3 MB / 7400 glyphs;
a typical app uses a handful, so the embedded array shrinks accordingly.

Driven from CMake (see CMakeLists.txt); also runnable by hand for debugging:

    python tools/gen_icon_font.py \
        --ttf materialdesignicons-webfont.ttf \
        --defines src/IconsMaterialDesignIcons.h \
        --out build/generated/icon_font_data.h \
        src/App.cpp src/App.h ...
"""
import argparse
import io
import os
import re
import sys

# ICON_MDI_FOO  "<utf8 bytes>"  // U+F0934
_DEFINE_RE = re.compile(r'#define\s+(ICON_MDI_[A-Z0-9_]+)\s+"[^"]*"\s*//\s*U\+([0-9A-Fa-f]+)')
_TOKEN_RE = re.compile(r'\bICON_MDI_[A-Z0-9_]+\b')


def parse_defines(path):
    """macro name -> codepoint, from the IconFontCppHeaders defines file."""
    table = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = _DEFINE_RE.search(line)
            if m:
                table[m.group(1)] = int(m.group(2), 16)
    if not table:
        sys.exit(f"gen_icon_font: no ICON_MDI_* defines parsed from {path}")
    return table


def scan_used(sources, defines_path):
    """Set of ICON_MDI_* tokens referenced across the source files.

    The defines header itself is skipped so its 7400 definitions don't count as
    'used'.
    """
    defines_real = os.path.realpath(defines_path)
    used = set()
    for path in sources:
        if os.path.realpath(path) == defines_real:
            continue
        try:
            with open(path, encoding="utf-8", errors="ignore") as f:
                text = f.read()
        except OSError:
            continue
        used.update(_TOKEN_RE.findall(text))
    return used


def write_header(out_path, data, var):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", newline="\n") as f:
        f.write("// Embedded subset of the Material Design Icons webfont.\n")
        f.write("// AUTO-GENERATED by tools/gen_icon_font.py from the ICON_MDI_* identifiers\n")
        f.write("// referenced in the source. Do not edit by hand; re-run the build to refresh.\n")
        f.write("#pragma once\n\n")
        f.write(f"static const unsigned char {var}[] = {{\n")
        row = []
        for b in data:
            row.append("0x%02x," % b)
            if len(row) == 20:
                f.write("".join(row) + "\n")
                row = []
        if row:
            f.write("".join(row) + "\n")
        f.write("};\n")
        f.write(f"static const unsigned int {var}_len = {len(data)};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ttf", required=True, help="source webfont .ttf")
    ap.add_argument("--defines", required=True, help="IconsMaterialDesignIcons.h")
    ap.add_argument("--out", required=True, help="output icon_font_data.h")
    ap.add_argument("--var", default="g_mdi_font_ttf", help="C array variable name")
    ap.add_argument("sources", nargs="+", help="source files to scan for ICON_MDI_* usage")
    args = ap.parse_args()

    try:
        from fontTools import subset
        from fontTools.ttLib import TTFont
    except ImportError:
        sys.exit(f"gen_icon_font: fonttools is required. Install with: pip install fonttools {sys.executable}")

    macro_cp = parse_defines(args.defines)
    used = scan_used(args.sources, args.defines)

    unknown = sorted(t for t in used if t not in macro_cp)
    if unknown:
        # Tokens that look like icons but aren't in the defines file: warn, don't fail.
        print("gen_icon_font: warning: unknown ICON_MDI_* tokens ignored: "
              + ", ".join(unknown), file=sys.stderr)

    codepoints = sorted({macro_cp[t] for t in used if t in macro_cp})
    if not codepoints:
        # Keep a valid (tiny) font so the embed/compile still works; the app's
        # glyph lookups will simply miss and fall back.
        print("gen_icon_font: warning: no ICON_MDI_* icons referenced; "
              "embedding an empty subset", file=sys.stderr)

    font = TTFont(args.ttf)
    options = subset.Options()
    options.notdef_outline = True       # keep .notdef so unknown glyphs render a box
    options.recalc_bounds = True
    options.drop_tables += ["GSUB", "GPOS"]  # no shaping needed for standalone icons
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)

    buf = io.BytesIO()
    font.save(buf)
    data = buf.getvalue()

    write_header(args.out, data, args.var)

    names = sorted(t for t in used if t in macro_cp)
    print("gen_icon_font: %d icon(s) -> %d bytes: %s"
          % (len(codepoints), len(data), ", ".join(names) if names else "(none)"))


if __name__ == "__main__":
    main()
