# Build-time version stamp. Run as `cmake -P` by the jplay_version target rather
# than at configure time, so the git state is re-read on every build instead of
# freezing at whenever cmake last ran. Writes JPLAY_OUT only when the contents
# change, so an unchanged commit does not rebuild the About panel.
#
# Expects: JPLAY_SRC_DIR, JPLAY_VERSION, JPLAY_OUT.

set(_hash "unknown")
set(_date "unknown")

find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${JPLAY_SRC_DIR}"
        OUTPUT_VARIABLE _hash_out OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _hash_out)
        set(_hash "${_hash_out}")
        # A tree with uncommitted edits is not the commit it names, and in
        # development most local builds are exactly that — mark them, or the
        # hash in a bug report lies about what was running.
        execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
            WORKING_DIRECTORY "${JPLAY_SRC_DIR}"
            OUTPUT_VARIABLE _dirty ERROR_QUIET)
        if(NOT _dirty STREQUAL "")
            string(APPEND _hash "-dirty")
        endif()
        # The commit date, not the build date: two builds of the same source then
        # stamp identically, and the date answers "how old is this code".
        execute_process(COMMAND "${GIT_EXECUTABLE}" log -1 --format=%cd --date=short
            WORKING_DIRECTORY "${JPLAY_SRC_DIR}"
            OUTPUT_VARIABLE _date_out OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(_date_out)
            set(_date "${_date_out}")
        endif()
    endif()
endif()

file(WRITE "${JPLAY_OUT}.tmp"
"// Generated by cmake/version.cmake on every build. Do not edit, do not commit.
#pragma once

#define JPLAY_VERSION  \"${JPLAY_VERSION}\"
#define JPLAY_GIT_HASH \"${_hash}\"
#define JPLAY_GIT_DATE \"${_date}\"
")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
    "${JPLAY_OUT}.tmp" "${JPLAY_OUT}")
file(REMOVE "${JPLAY_OUT}.tmp")
